# -*- coding: utf-8 -*-
"""student_employability_app_final.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-3dqWEVtZ9vWPIW7UxmFxQEr8itV66I
"""

# advanced_employability_app_final.py

# File: streamlit_app.py

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# --- Configuration ---
st.set_page_config(page_title="Student Employability Predictor", layout="centered")

# --- Load Model and Scaler ---
try:
    model = joblib.load('employability_predictor.pkl')
    scaler = joblib.load('scaler.pkl')
    st.success("Model and Scaler loaded successfully!")
except FileNotFoundError:
    st.error("""
        Error: Model or scaler file not found.
        Please ensure 'employability_predictor.pkl' and 'scaler.pkl' are in the same directory.
    """)
    st.stop()

st.title("🎓 Student Employability Prediction App")
st.markdown("""
    Welcome to the Student Employability Predictor! Adjust the sliders and options below to test different scenarios.
""")
st.markdown("---")

st.header("Enter Student Attributes")

col1, col2 = st.columns(2)

feature_columns = [
    'STUDENT_PERFORMANCE_RATING', 'PROJECT_COMPLETION_RATE', 'INTERNSHIP_EXPERIENCE',
    'COMMUNICATION_SKILLS', 'PROBLEM_SOLVING_SKILLS', 'TEAMWORK_SKILLS',
    'LEADERSHIP_SKILLS', 'CRITICAL_THINKING_SKILLS', 'ADAPTABILITY',
    'TIME_MANAGEMENT_SKILLS', 'GPA', 'EXTRACURRICULAR_ACTIVITIES',
    'VOLUNTEERING_EXPERIENCE', 'CERTIFICATIONS', 'WORK_EXPERIENCE',
    'CAREER_GOALS_ALIGNMENT', 'JOB_FAIR_ATTENDANCE', 'NETWORKING_EVENTS_ATTENDED',
    'MOCK_INTERVIEW_PERFORMANCE', 'RESUME_STRENGTH', 'RECOMMENDATION_LETTERS',
    'ONLINE_PRESENCE', 'SOFT_SKILLS_ASSESSMENT', 'TECHNICAL_SKILLS_ASSESSMENT',
    'ATTENDANCE_RATE', 'PRACTICAL_SKILLS_SCORE', 'RESEARCH_PAPER_PUBLISHED',
    'AWARDS_ACHIEVEMENTS', 'ENTREPRENEURIAL_INITIATIVES', 'GLOBAL_EXPOSURE'
]

input_values = {}

with col1:
    st.subheader("Academic & Core Skills")
    input_values['STUDENT_PERFORMANCE_RATING'] = st.slider("Student Performance Rating (1-5)", 1.0, 5.0, 3.5, 0.1)
    input_values['PROJECT_COMPLETION_RATE'] = st.slider("Project Completion Rate (%)", 0.0, 100.0, 85.0, 1.0)
    input_values['GPA'] = st.number_input("GPA (0.0-4.0)", 0.0, 4.0, 3.2, 0.01)
    input_values['ATTENDANCE_RATE'] = st.slider("Attendance Rate (%)", 0.0, 100.0, 92.0, 1.0)
    input_values['PRACTICAL_SKILLS_SCORE'] = st.slider("Practical Skills Score (1-5)", 1.0, 5.0, 3.8, 0.1)
    input_values['COMMUNICATION_SKILLS'] = st.slider("Communication Skills (1-5)", 1.0, 5.0, 4.0, 0.1)
    input_values['PROBLEM_SOLVING_SKILLS'] = st.slider("Problem Solving Skills (1-5)", 1.0, 5.0, 4.2, 0.1)
    input_values['CRITICAL_THINKING_SKILLS'] = st.slider("Critical Thinking Skills (1-5)", 1.0, 5.0, 4.1, 0.1)
    input_values['ADAPTABILITY'] = st.slider("Adaptability (1-5)", 1.0, 5.0, 3.9, 0.1)
    input_values['TIME_MANAGEMENT_SKILLS'] = st.slider("Time Management Skills (1-5)", 1.0, 5.0, 3.7, 0.1)

with col2:
    st.subheader("Experience & Professional Development")
    for name, default in [
        ('INTERNSHIP_EXPERIENCE', 1), ('EXTRACURRICULAR_ACTIVITIES',1), ('VOLUNTEERING_EXPERIENCE',0),
        ('CERTIFICATIONS',1), ('WORK_EXPERIENCE',0), ('JOB_FAIR_ATTENDANCE',1), ('NETWORKING_EVENTS_ATTENDED',0),
        ('RESEARCH_PAPER_PUBLISHED',0), ('AWARDS_ACHIEVEMENTS',1), ('ENTREPRENEURIAL_INITIATIVES',0), ('GLOBAL_EXPOSURE',0),
        ('RECOMMENDATION_LETTERS',1)
    ]:
        input_values[name] = st.radio(name.replace('_',' ').title(), [0,1], format_func=lambda x: "Yes" if x==1 else "No", index=default)

    input_values['CAREER_GOALS_ALIGNMENT'] = st.slider("Career Goals Alignment (1-5)", 1.0, 5.0, 4.0, 0.1)
    input_values['MOCK_INTERVIEW_PERFORMANCE'] = st.slider("Mock Interview Performance (1-5)", 1.0, 5.0, 3.5, 0.1)
    input_values['RESUME_STRENGTH'] = st.slider("Resume Strength (1-5)", 1.0, 5.0, 4.0, 0.1)
    input_values['ONLINE_PRESENCE'] = st.slider("Online Presence (1-5)", 1.0, 5.0, 3.0, 0.1)
    input_values['SOFT_SKILLS_ASSESSMENT'] = st.slider("Soft Skills Assessment (1-5)", 1.0, 5.0, 3.9, 0.1)
    input_values['TECHNICAL_SKILLS_ASSESSMENT'] = st.slider("Technical Skills Assessment (1-5)", 1.0, 5.0, 4.1, 0.1)
    input_values['TEAMWORK_SKILLS'] = st.slider("Teamwork Skills (1-5)", 1.0, 5.0, 4.0, 0.1)
    input_values['LEADERSHIP_SKILLS'] = st.slider("Leadership Skills (1-5)", 1.0, 5.0, 3.5, 0.1)

input_df = pd.DataFrame([input_values], columns=feature_columns)

if st.button("Predict Employability"):
    st.subheader("Prediction Results:")

    # 🪄 Fix: reorder columns to match scaler’s expected order
    input_df = input_df[scaler.feature_names_in_]

    scaled_input = scaler.transform(input_df)

    prediction = model.predict(scaled_input)
    prediction_proba = model.predict_proba(scaled_input)

    if prediction[0] == 1:
        st.success("🎉 The student is predicted to be **Employable**!")
        st.balloons()
    else:
        st.warning("⚠️ The student is predicted to be **Less Employable**.")

    st.info(f"**Probability of being Employable:** {prediction_proba[0][1]*100:.2f}%")
    st.info(f"**Probability of being Less Employable:** {prediction_proba[0][0]*100:.2f}%")

    st.markdown("""
        <small><i>Disclaimer: This prediction is based on the trained machine learning model and the attributes you provided. Use as guidance only.</i></small>
    """, unsafe_allow_html=True)

st.markdown("---")
st.caption("© 2025 CHOONG MUH IN / APU University | Graduate Employability Prediction App | For research purposes only.")


# File: requirements.txt
"""
streamlit>=1.33
joblib>=1.4
pandas>=2.2
numpy>=1.26
scikit-learn>=1.4
"""

# File: .gitignore
"""
__pycache__/
*.pyc
*.pkl
*.joblib
*.pdf
.ipynb_checkpoints/
.env
*.env
.vscode/
.idea/
"""

# File: README.md
"""
# 🎓 Student Employability Predictor

Interactive Streamlit app to predict employability based on 30+ attributes.

## 🚀 How to Run

### Local
```bash
pip install -r requirements.txt
streamlit run streamlit_app.py
```

### Streamlit Cloud
✅ Push to GitHub with `streamlit_app.py`, `employability_predictor.pkl`, `scaler.pkl`  
✅ Deploy on https://streamlit.io/cloud

## 📂 Files
- `streamlit_app.py` → main app
- `employability_predictor.pkl` → trained model
- `scaler.pkl` → data scaler
- `requirements.txt` → dependencies
- `.gitignore` → recommended ignores
- `README.md` → this file

---
© 2025 CHOONG MUH IN / APU University
"""

# --- Footer Information ---
# Displays version, update, developer, and copyright information at the bottom of the page.
st.markdown("""
    <div class="footer-info">
        Version 1.0 | Last updated: Aug-2025 | Developed by Mr.CHOONG MUH IN (TP068331)
    </div>
    """, unsafe_allow_html=True)
st.caption("© 2025 CHOONG MUH IN / APU University | Graduate Employability Prediction App | For research purposes only.")
